apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
    service: app2
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: app2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app2
  labels:
    account: app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-v1
  labels:
    app: app2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app: app2
        version: v1
    spec:
      serviceAccountName: demo-app2
      containers:
      - name: app2
        image: ttl.sh/iblancasa/demo-app2
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
---
