apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: istio-system
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: tracing-system
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - demo
  - tracing-system
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  addons:
    grafana:
      enabled: true
    prometheus:
      enabled: true
    kiali:
      enabled: true
  tracing:
    type: None
  meshConfig:
    extensionProviders:
      - name: tempo
        zipkin:
          service: tempo-sample-distributor.tracing-system.svc.cluster.local
          port: 9411
  version: v2.5
